'use strict';
const $=id=>document.getElementById(id);
const token=document.querySelector('meta[name="fleetmesh-token"]').content;
const colors=['#4ade80','#67c6f4','#f7c16b','#b4a0f5','#fb9aa3','#63ddd0'];
const escapeHTML=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const title=value=>String(value||'').replaceAll('_',' ').replace(/\b\w/g,c=>c.toUpperCase());
const number=(value,digits=1)=>Number(value||0).toFixed(digits);
let live=null,replay=null,view='overview',pending=false,mapKey='',lastEvents='',lastJobs='',polling=false;
let selectedRobot=0,mapHits=[];
let toastTimer, lastCommandError='', stopTarget=null, robotKey='', connected=false;
const put=(id,text)=>{if($(id).textContent!==String(text))$(id).textContent=String(text)};
const shown=()=>replay?replay.frames[replay.index]:live;
async function fetchJSON(url,options={},timeout=6000){const controller=new AbortController();const timer=setTimeout(()=>controller.abort(),timeout);try{const response=await fetch(url,{...options,signal:controller.signal});const result=await response.json();if(!response.ok){const error=Error(result.error||'Request failed');error.serverResponse=true;throw error}return result}finally{clearTimeout(timer)}}
function toast(message){$('toast').textContent=message;$('toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').hidden=true,5000)}
function setView(name){if(name!=='overview'&&typeof setPresentation==='function')setPresentation(false);view=name;document.querySelectorAll('.view').forEach(node=>node.hidden=node.id!=='view-'+name);document.querySelectorAll('nav [data-view]').forEach(node=>node.classList.toggle('active',node.dataset.view===name));const copy={overview:['Overview','Every robot. One clear view.','Inspect local decisions, shared road zones and delivery progress.'],missions:['Missions','Work with clear ownership.','Submit missions and inspect each handoff, pickup and delivery.'],evidence:['Benchmarks','Evidence behind the decisions.','Compare the complete system with simpler policies on identical work.'],history:['Run history','Every experiment, recorded.','Replay a run and export the evidence from your local workspace.'],review:['Run review','From a run to a clear result.','Inspect observed outcomes and the evidence behind each claim.']};$('breadcrumb').textContent=copy[name][0];$('page-title').textContent=copy[name][1];$('page-description').textContent=copy[name][2];if(name==='history')loadHistory();if(name==='overview'&&(replay||live))draw(replay?replay.frames[replay.index]:live)}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>setView(button.dataset.view)));
document.querySelectorAll('[data-close]').forEach(button=>button.addEventListener('click',()=>$(button.dataset.close).close()));
async function command(action,data={}){
 if(pending)return false;
 pending=true;lastCommandError='';document.body.setAttribute('aria-busy','true');if(shown())render(shown(),!!replay);
 const requestId=typeof crypto!=='undefined'&&crypto.randomUUID?crypto.randomUUID():Date.now().toString(36)+'-'+Math.random().toString(36).slice(2);
 try{
  for(let attempt=0;attempt<2;attempt++){
   try{await fetchJSON('/api/'+action,{method:'POST',headers:{'Content-Type':'application/json','X-FleetMesh-Token':token,'X-FleetMesh-Request-ID':requestId},body:JSON.stringify(data)},45000);break}
   catch(error){if(error.serverResponse)throw error;if(attempt===1)throw Error('The command outcome is unconfirmed. Check the latest run before repeating it.')}
  }
  await poll();return true;
 }catch(error){lastCommandError=error.message;toast(error.message);return false}
 finally{pending=false;document.body.removeAttribute('aria-busy');if(shown())render(shown(),!!replay)}
}
function formError(id,message=''){$(id).hidden=!message;put(id,message)}
$('new-run').onclick=()=>{formError('experiment-error');$('experiment-dialog').showModal()};
$('experiment-form').onsubmit=async event=>{event.preventDefault();formError('experiment-error');const values=Object.fromEntries(new FormData(event.currentTarget));for(const key of ['robots','jobs','seed'])values[key]=Number(values[key]);const button=event.currentTarget.querySelector('[type="submit"]');button.disabled=true;button.textContent='Launching…';if(await command('start',values)){replay=null;mapKey='';$('experiment-dialog').close();setView('overview');toast('Robot processes launched');render(live)}else formError('experiment-error',lastCommandError);button.disabled=false;button.textContent='Launch experiment'};
$('add-job').onclick=()=>{if(!live?.run_id)return toast('Start an experiment first');formError('job-error');$('job-dialog').showModal()};
$('job-form').onsubmit=async event=>{event.preventDefault();const values=Object.fromEntries(new FormData(event.currentTarget));values.priority=Number(values.priority);formError('job-error');if(values.pickup===values.drop)return formError('job-error','Choose different pickup and delivery stations');if(await command('job',values)){$('job-dialog').close();toast('Mission submitted to peer auction')}else formError('job-error',lastCommandError)};
$('launch-demo').onclick=async()=>{if(await command('demo')){replay=null;mapKey='';setView('overview');render(live);toast('Disruption demo launched. Actions follow simulated time.')}};
$('pause').onclick=()=>command('pause');$('speed').onchange=event=>command('speed',{rate:Number(event.target.value)});
$('network').onclick=()=>command('network',{partitioned:!live?.partitioned});
$('close-aisle').onclick=()=>command('aisle',{edge:$('aisle').value,blocked:true});$('open-aisle').onclick=()=>command('aisle',{edge:$('aisle').value,blocked:false});
$('robots').onclick=event=>{const button=event.target.closest('button[data-robot]');if(!button)return;const rid=Number(button.dataset.robot);if(button.dataset.action==='inspect'){selectedRobot=rid;render(shown(),!!replay);return}if(pending||replay)return;if(button.dataset.action==='kill'){stopTarget=rid;put('stop-title','Stop Robot '+(rid+1)+' process?');$('stop-dialog').showModal()}else command('maintenance',{robot:rid,available:!live.robots[rid].available})};
$('refresh-history').onclick=loadHistory;
$('confirm-stop').onclick=async()=>{if(stopTarget===null)return;if(await command('kill',{robot:stopTarget})){$('stop-dialog').close();stopTarget=null}};
$('mission-query').oninput=()=>{if(shown())renderJobs(shown())};
$('mission-filter').onchange=()=>{if(shown())renderJobs(shown())};
$('aisle').onchange=()=>{if(shown())renderAisle(shown())};
$('replay-slider').oninput=event=>{if(replay){replay.playing=false;replay.index=Number(event.target.value);replay.clock=Number(replay.frames[replay.index].time);render(replay.frames[replay.index],true)}};
$('exit-replay').onclick=()=>{replay=null;mapKey='';lastEvents='';lastJobs='';if(live)render(live)};
function render(state,isReplay=false){const active=!!state.robots?.length&&!isReplay&&connected&&!pending&&['running','paused'].includes(state.status);const canAdd=!!state.robots?.length&&!isReplay&&connected&&!pending&&['running','paused','completed'].includes(state.status);const completed=state.complete===state.total_jobs&&state.total_jobs>0;$('connection').textContent=isReplay?'Recorded replay':state.error?'Run error':state.playing?'Live simulation':completed?'Run complete':state.status==='paused'?'Simulation paused':state.status==='timeout'?'Run timed out':'Local / ready';$('run-label').textContent=isReplay?'Viewing a saved experiment':state.run_id?`Run ${state.run_id.slice(0,8)} · ${title(state.map.name)} · ${state.robots.length} agents`:'Ready to begin';$('metric-time').innerHTML=number(state.time)+'<small>s</small>';$('metric-jobs').innerHTML=(state.complete||0)+`<small>/ ${state.total_jobs||0}</small>`;$('metric-wait').innerHTML=number(state.wait_seconds)+'<small>s</small>';$('metric-collisions').textContent=state.collisions||0;$('metric-deliveries').textContent=(state.delivered||0)+' packages delivered';$('metric-separation').textContent=state.minimum_separation===null?'Swept-body collision checks':`Minimum separation ${number(state.minimum_separation,2)} m`;
$('pause').textContent=state.playing?'Pause':'Resume';$('pause').disabled=!active||completed||['failed','timeout'].includes(state.status);$('speed').disabled=isReplay||!connected||pending;$('new-run').disabled=!connected||pending||isReplay;$('confirm-stop').disabled=!active;$('network').disabled=!active;$('network').textContent=state.partitioned?'Restore peer network':'Interrupt peer network';$('network').classList.toggle('primary',!!state.partitioned);for(const id of ['close-aisle','open-aisle'])$(id).disabled=!active;$('add-job').disabled=!canAdd;$('replay-controls').hidden=!isReplay;
const policy=state.policy||live?.policy||'heuristic';$('policy-note').textContent={baseline:'Shortest routes. Road zones acquired sequentially.',atomic:'Shortest routes. Whole-route peer permission.',heuristic:'Whole-route permission plus a fixed queue-delay rule.',predictive:'Whole-route permission plus a learned queue-delay model.'}[policy];$('map-subtitle').textContent=`${title(state.map.name)} · ${state.map.stations.length} road zones · private parking docks`;
const offline=state.robots?.filter(r=>!r.alive).length||0;const warning=isReplay?'Replay displays recorded frames. The live experiment continues independently.':state.error?state.error:offline?'An agent is offline. Its grants and held zones do not expire. Start a new run for a clean recovery.':state.partitioned?'Peer messages are interrupted. Existing permissions remain valid; new requests may wait.':state.status==='timeout'?'The experiment reached its 900-second simulation limit. Inspect the event record.':null;$('notice').hidden=!warning;put('notice',warning||'');
const key=state.map.name+'-'+state.map.homes.length;if(mapKey!==key){mapKey=key;const opts=state.map.stations.map(n=>`<option value="${n}">${n}</option>`).join('');$('pickup').innerHTML=opts;$('drop').innerHTML=opts;$('drop').selectedIndex=Math.min(1,state.map.stations.length-1);$('aisle').innerHTML=state.map.edges.filter(([a,b])=>a.startsWith('N')&&b.startsWith('N')).map(([a,b])=>{const key=[a,b].sort().join(':');return `<option value="${key}">${a} — ${b}</option>`}).join('')}
renderRobots(state,isReplay,active);renderAisle(state);
const events=JSON.stringify(state.events||[]);if(events!==lastEvents){lastEvents=events;$('events').innerHTML=state.events?.length?state.events.slice().reverse().map(event=>`<div class="event-row"><span class="event-time">${number(event.time)} s</span><span class="event-kind">${escapeHTML(event.kind)}</span><span>${event.robot===null?'':`R${event.robot+1} · `}${escapeHTML(event.detail)}</span></div>`).join(''):'<p class="empty-text">Robot decisions will appear here during a run.</p>';$('activity-count').textContent=(state.events?.length||0)+' recent events'}
renderJobs(state);
const demo=state.demonstration;
$('launch-demo').disabled=pending||!connected||isReplay;
const stages=[[5,'urgent','Urgent job'],[12,'close','Aisle closes'],[20,'interrupt','Messages stop'],[28,'restore','Messages return'],[45,'reopen','Aisle reopens']];
$('demo-actions').innerHTML=stages.map(([time,key,label])=>{const action=demo?.actions?.find(a=>a.action===key);return `<li class="${action?'applied':''}" title="${escapeHTML(action?.detail||'Scheduled at '+time+' simulated seconds')}"><span>${action?'✓':'○'} ${time} s</span><strong>${label}</strong></li>`}).join('');
put('demo-outcome',demo?`${demo.actions.length}/${demo.scheduled_actions} stages applied · ${state.complete}/${state.total_jobs} missions complete · ${state.collisions||0} detected collisions${completed?' · All missions returned to dock.':['failed','timeout'].includes(state.status)?' · Run ended incomplete.':!state.playing?' · Paused.':''}`:'Launch to observe the decisions and download the result.');
$('demo-report').hidden=!state.run_id||!demo||isReplay;
if(state.run_id)$('demo-report').href='/api/runs/'+state.run_id+'/report';
if(typeof renderWorkspace==='function')renderWorkspace(state,isReplay);if(view==='overview')draw(state)}
function renderAisle(state){const key=$('aisle').value;const queued=state.pending_closures?.includes(key);const closed=state.map_changes?.[key]?.blocked;put('aisle-state',queued?'Closure queued: waiting for the segment to clear.':closed?'This aisle is closed. Reopen it to restore access.':'This aisle is open. A closure waits for the segment to clear.')}
function renderRobots(state,isReplay,active){
 const robots=state.robots||[],key=(state.run_id||'none')+':'+robots.map(r=>r.id).join(',');
 if(key!==robotKey){robotKey=key;$('robots').innerHTML=robots.length?robots.map(r=>`<article class="robot-card"><div class="robot-top"><button id="robot-inspect-${r.id}" class="robot-name inspect-button" data-action="inspect" data-robot="${r.id}" aria-label="Inspect Robot ${r.id+1}"><i class="robot-color" style="background:${colors[r.id]}"></i>Robot ${r.id+1}</button><span id="robot-status-${r.id}" class="status"></span></div><p id="robot-reason-${r.id}" class="robot-reason"></p><div class="robot-numbers"><div><span>Mission</span><b id="robot-job-${r.id}"></b></div><div><span>Zones held</span><b id="robot-zones-${r.id}"></b></div><div><span>Waiting</span><b id="robot-wait-${r.id}"></b></div></div><details class="robot-details"><summary>Process details</summary><div id="robot-meta-${r.id}" class="robot-meta"></div></details><div class="robot-actions"><button id="robot-maintain-${r.id}" data-action="maintenance" data-robot="${r.id}"></button><button id="robot-stop-${r.id}" class="stop" data-action="kill" data-robot="${r.id}">Stop process</button></div></article>`).join(''):'<div class="empty-state"><strong>Your fleet is ready to launch.</strong><p>Launch the demo or configure a new experiment.</p></div>'}
 for(const r of robots){const status=!r.alive?'offline':!r.available?'maintenance':r.stage==='idle'?'docked':r.stage;put('robot-status-'+r.id,status);$('robot-status-'+r.id).classList.toggle('error',!r.alive);$('robot-status-'+r.id).classList.toggle('active',!!r.active&&r.alive);put('robot-reason-'+r.id,r.reason);put('robot-job-'+r.id,r.active||'—');put('robot-zones-'+r.id,r.held.length);put('robot-wait-'+r.id,number(r.wait_seconds)+' s');$('robot-meta-'+r.id).innerHTML=`Node ${escapeHTML(r.node||r.home||'—')} · Held zones ${escapeHTML(r.held.join(', ')||'none')}<br>PID ${r.pid||'—'} · ${(r.sent||0).toLocaleString()} sent · ${(r.received||0).toLocaleString()} received<br>Distance ${number(r.distance)} m · Simulated battery ${number(r.battery)}%<br>Controller step ${number(r.step_ms,3)} ms · Peer grants ${r.grants} / ${robots.length-1}`;put('robot-maintain-'+r.id,r.available?'Request maintenance':'Return to service');$('robot-maintain-'+r.id).disabled=!active||!r.alive;$('robot-stop-'+r.id).disabled=!active||!r.alive}
 put('fleet-summary',robots.length?`${robots.filter(r=>r.alive).length} online · ${state.transfers||0} ownership transfers · ${state.reroutes||0} route recoveries`:'Start an experiment to launch agents');
}
function renderJobs(state){
 const query=($('mission-query').value||'').trim().toLowerCase(),filter=$('mission-filter').value||'all';const key=JSON.stringify([state.jobs,query,filter]);if(key===lastJobs)return;lastJobs=key;
 const jobs=(state.jobs||[]).filter(j=>(filter==='all'||filter==='open'&&j.state!=='done'||filter==='urgent'&&j.priority===3||filter==='done'&&j.state==='done')&&`${j.id} ${j.pickup} ${j.drop} robot ${j.owner+1}`.toLowerCase().includes(query));
 $('jobs-table').innerHTML=jobs.length?jobs.map(j=>`<tr><td><strong>${escapeHTML(j.id)}</strong></td><td>${escapeHTML(j.pickup)}</td><td>${escapeHTML(j.drop)}</td><td><span style="color:${colors[j.owner]}">Robot ${j.owner+1}</span></td><td>${['','Normal','High','Urgent'][j.priority]}</td><td><span class="status ${j.state==='done'?'done':''}">${escapeHTML(title(j.state))}</span></td><td>${j.delivered_at===undefined?'—':number(j.delivered_at)+' s'}</td></tr>`).join(''):`<tr><td colspan="7" class="empty-text">${state.jobs?.length?'No missions match these filters.':'No missions yet. Start an experiment to create a workload.'}</td></tr>`;put('mission-count',`${jobs.length} of ${state.jobs?.length||0} missions`)
}
function draw(state){mapHits=[];if(!state?.map)return;const canvas=$('floor');const rect=canvas.getBoundingClientRect();if(!rect.width)return;const ratio=Math.min(window.devicePixelRatio||1,2);canvas.width=rect.width*ratio;canvas.height=rect.height*ratio;const ctx=canvas.getContext('2d');ctx.scale(ratio,ratio);const width=rect.width,height=rect.height,nodes=state.map.nodes,positions=Object.values(nodes),xs=positions.map(p=>p[0]),ys=positions.map(p=>p[1]);const minX=Math.min(...xs)-1,maxX=Math.max(...xs)+1,minY=Math.min(...ys)-1,maxY=Math.max(...ys)+1;const scale=Math.min((width-74)/(maxX-minX),(height-66)/(maxY-minY));const ox=(width-(maxX-minX)*scale)/2,oy=(height-(maxY-minY)*scale)/2;const xy=p=>[ox+(p[0]-minX)*scale,oy+(maxY-p[1])*scale];ctx.fillStyle='#091725';ctx.fillRect(0,0,width,height);ctx.fillStyle='#203446';for(let x=15;x<width;x+=18)for(let y=15;y<height;y+=18){ctx.beginPath();ctx.arc(x,y,.7,0,Math.PI*2);ctx.fill()}
for(const [a,b] of state.map.edges){const key=[a,b].sort().join(':'),closed=state.map_changes?.[key]?.blocked,queued=state.pending_closures?.includes(key);ctx.beginPath();ctx.moveTo(...xy(nodes[a]));ctx.lineTo(...xy(nodes[b]));ctx.strokeStyle=closed?'#c97972':queued?'#edbd63':a.startsWith('H')||b.startsWith('H')?'#263e4c':'#1d3446';ctx.lineWidth=11;ctx.lineCap='round';ctx.stroke();if(closed){const middle=xy([(nodes[a][0]+nodes[b][0])/2,(nodes[a][1]+nodes[b][1])/2]);ctx.fillStyle='#ffb0a7';ctx.font='bold 14px sans-serif';ctx.textAlign='center';ctx.fillText('×',middle[0],middle[1]+5)}}
for(const robot of state.robots||[]){if(!robot.route?.length)continue;ctx.strokeStyle=colors[robot.id]+(robot.id===selectedRobot?'dd':'40');ctx.lineWidth=robot.id===selectedRobot?3:1.5;ctx.setLineDash([4,6]);ctx.beginPath();ctx.moveTo(...xy(robot.position));for(const node of robot.route.slice(1))ctx.lineTo(...xy(nodes[node]));ctx.stroke();ctx.setLineDash([])}
for(const [name,pos] of Object.entries(nodes)){const [x,y]=xy(pos),owners=(state.robots||[]).filter(robot=>robot.held?.includes(name));ctx.beginPath();if(name.startsWith('H')){ctx.rect(x-9,y-9,18,18);ctx.fillStyle='#20453b'}else{ctx.arc(x,y,owners.length?10:4,0,Math.PI*2);ctx.fillStyle=owners.length?colors[owners[0].id]+'2b':'#50768a'}ctx.fill();if(owners.length){ctx.lineWidth=1.5;ctx.strokeStyle=colors[owners[0].id];ctx.stroke()}ctx.textAlign='center';ctx.font='11px sans-serif';ctx.fillStyle='#8eabc0';ctx.fillText(name.startsWith('H')?'DOCK '+(Number(name.slice(1))+1):name,x,y+22)}
for(const robot of state.robots||[]){const [x,y]=xy(robot.position);mapHits.push({x,y,id:robot.id});if(robot.id===selectedRobot){ctx.beginPath();ctx.arc(x,y,18,0,Math.PI*2);ctx.strokeStyle=colors[robot.id];ctx.lineWidth=2;ctx.stroke()}ctx.shadowBlur=7;ctx.shadowColor='#4ade8066';ctx.beginPath();ctx.arc(x,y,12,0,Math.PI*2);ctx.fillStyle=robot.alive?colors[robot.id]:'#5c6d7b';ctx.fill();ctx.shadowBlur=0;ctx.lineWidth=2.5;ctx.strokeStyle='#091725';ctx.stroke();ctx.fillStyle='#071724';ctx.font='bold 11px sans-serif';ctx.textAlign='center';ctx.fillText(robot.id+1,x,y+4)}ctx.fillStyle='#7895ad';ctx.textAlign='left';ctx.font='11px sans-serif';ctx.fillText('SIMULATED FLOOR / METRES',18,height-14)}
async function poll(){if(polling)return;polling=true;try{live=await fetchJSON('/api/state');connected=true;if(!replay)render(live)}catch(error){connected=false;if(shown())render(shown(),!!replay);put('connection','Connection lost');$('notice').hidden=false;put('notice','The local server is unavailable. Check that the FleetMesh terminal is still running.')}finally{polling=false}}
async function loadEvidence(){try{const data=await fetchJSON('/api/evidence');$('evidence-stats').innerHTML=[['Evaluated runs',data.total_runs||0,'Fixed paired experiments'],['Completed',data.completed||0,'All missions returned to dock'],['Detected collisions',data.collisions||0,'Finite simulated observations'],['Training samples',data.training?.training_samples||0,'Observed road-zone waiting times']].map(([label,value,caption])=>`<article><span>${label}</span><strong>${value}</strong><p>${caption}</p></article>`).join('');$('evidence-table').innerHTML=(data.cohorts||[]).map(row=>`<tr><td><strong>${title(row.map)}</strong><br><small>${title(row.scenario)} / ${row.seeds} seeds</small></td><td>${number(row.mean_seconds.baseline,2)}</td><td>${number(row.mean_seconds.atomic,2)}</td><td>${number(row.mean_seconds.heuristic,2)}</td><td>${number(row.mean_seconds.predictive,2)}</td><td class="${row.predictive_change_pct>=0?'positive':'negative'}">${Math.abs(row.predictive_change_pct).toFixed(1)}% ${row.predictive_change_pct>=0?'less':'more'} time</td></tr>`).join('');$('evidence-limits').textContent=`Training: ${data.training?.training_map||'unavailable'} map. ${data.metric||''}. ${(data.limits||[]).join(' ')}`}catch(error){toast('Benchmark file unavailable. Run evaluate.py to regenerate it.')}}
async function loadHistory(){try{const records=await fetchJSON('/api/runs');$('history-table').innerHTML=records.length?records.map(record=>`<tr><td>${escapeHTML(new Date(record.started).toLocaleString())}</td><td>${title(record.map)}<br><small>${title(record.mode)}</small></td><td>${record.seed}</td><td>${record.complete} / ${record.jobs}</td><td>${number(record.seconds)} s</td><td><span class="status ${record.status==='completed'?'done':''}">${title(record.status)}</span></td><td><button class="button" data-review="${record.id}">Review</button><button class="button" data-replay="${record.id}">Replay</button><a class="button" href="/api/runs/${record.id}?download=1">JSON</a><a class="button" href="/api/runs/${record.id}/csv">CSV</a><a class="button" href="/api/runs/${record.id}/report">Report</a></td></tr>`).join(''):'<tr><td colspan="7" class="empty-text">Completed and interrupted experiments will be saved here.</td></tr>'}catch(error){toast('Could not load run history')}}
$('history-table').onclick=async event=>{const button=event.target.closest('[data-replay], [data-review]');if(!button)return;if(button.dataset.review)await loadReview(button.dataset.review);else await openReplay(button.dataset.replay)};
window.addEventListener('resize',()=>{if(view==='overview')draw(replay?replay.frames[replay.index]:live)});
setInterval(poll,250);poll();loadEvidence();
